---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update package cache
      ansible.builtin.package: update_cache=yes
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
    - name: create containerd folder
      ansible.builtin.file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
        mode: 0755
      when: ansible_service_mgr == "systemd"
    - name: override file for containerd
      ansible.builtin.copy:
        src: files/override.conf
        dest: /etc/systemd/system/containerd.service.d/override.conf
        mode: 0644
      when: ansible_service_mgr == "systemd"
  tasks:
    - name: Fix for docker container images
      ansible.builtin.file:
        state: directory
        path: /usr/share/man/man1
        recurse: true
    - name: Molecule | Wavefront Proxy
      ansible.builtin.include_role:
        name: wavefront_proxy
      vars:
        wavefront_api_token: somerandomtokenvalue
