---
# defaults file for wavefront_proxy

wavefront_api_endpoint: https://vmwareprod.wavefront.com/api/
wavefront_proxy_port: 2878

wavefront_proxy_repo_url: https://packagecloud.io/wavefront/proxy
wavefront_proxy_repo_gpgkey: https://packagecloud.io/wavefront/proxy/gpgkey
wavefront_proxy_package: wavefront-proxy

wavefront_config_dir: /etc/wavefront/wavefront-proxy
