---
galaxy_info:
  role_name: wavefront_proxy
  author: Eric Anderson
  description: Role to install and configure Wavefront Proxy
  company: Avi Networks
  issue_tracker_url: https://https://gitlab.eng.vmware.com/aeric/ansible-collection-wavefront/issues
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "27"
        - "28"
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy
  galaxy_tags:
    - docker
    - ubuntu
    - centos
    - debian
dependencies: []
